version: '3.7'

services: 
  iris:
    init: true
    build: 
      context: .
      args:
        COMMIT_ID: ${COMMIT_ID}
    hostname: iris
    ports:
    - "1972:1972"
    - "52773:52773"
    - "63300:63300"  # foreground
    - "63301:63301"  # foreground
    command:
      --check-caps false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    cap_add:
    - IPC_LOCK
    networks:
    - iris-tier
    volumes:
    - ./ext:/opt/iris/ext
    - ./upload:/home/irisowner/upload
    - ./UserCPF:/home/irisowner/cpf
    depends_on:
    - postgres
    - sftp
    - ftp
    - smtp
    secrets:
      - yahoo_cred
      - gmail_cred
      - gmail_client_secret
  postgres:
    image: postgres:12.2-alpine
    hostname: postgres
    ports: 
    - "5432:5432"
    environment:
    - TZ=JST-9
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - PGPASSWORD=postgres
    - POSTGRES_DB=demo
    - DATABASE_HOST=localhost
    networks:
    - iris-tier
    volumes:
    - ./postgres/initdb:/docker-entrypoint-initdb.d    

  sftp:
    image: atmoz/sftp
    hostname: sftp
    volumes:
    - ./upload:/home/foo/upload
    ports:
    - "2222:22"
    environment:
    - TZ=JST-9
    command: foo:pass:1000:1000
    networks:
    - iris-tier

  ftp:
    image: stilliard/pure-ftpd
    hostname: ftp
    ports:
    - "2121:21"
    - "30000-30009:30000-30009"
    volumes:
    - ./upload:/home/foo/upload
    environment:
    - PUBLICHOST=ftp
    - FTP_USER_NAME=foo
    - FTP_USER_PASS=pass
    - FTP_USER_HOME=/home/foo
    - FTP_USER_UID=1000
    - FTP_USER_GID=1000
    networks:
      - iris-tier
  
  smtp:
    build: 
      context: smtp
    hostname: smtp.example.com
    ports:
    - "25:25"
    environment:
      - maildomain=smtp.example.com
      - smtp_user=foo:pass
    networks:
      - iris-tier

  iris2:
    build: 
      context: msgbank
      args:
        COMMIT_ID: ${COMMIT_ID}
    hostname: iris2
    ports:
    - "52774:52773"
    command:
      --check-caps false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    networks:
    - iris-tier
    volumes:
    - ./UserCPF:/home/irisowner/cpf
    depends_on:
    - iris

networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
      
secrets:
  yahoo_cred:
    file: ./yahoo_cred.json
  gmail_cred:
    file: ./gmail_cred.json
  gmail_client_secret:
    file: ./gmail_client_secret.json
