version: '3.7'

services: 
  iris:
    init: true
    image: dpmeister/iris-i14y
    build: 
      context: .
      args:
        COMMIT_ID: ${COMMIT_ID}
    hostname: iris
    ports:
    - 51773:51773
    - 52773:52773
    environment:
    - TZ=JST-9
    networks:
    - iris-tier
    volumes:
    - ./ext:/opt/iris/ext
    - ./upload:/home/irisowner/upload
    depends_on:
    - postgres
    - sftp
    - ftp

  postgres:
    image: postgres:12.2-alpine
    hostname: postgres
    ports: 
    - "5432:5432"
    environment:
    - TZ=JST-9
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - PGPASSWORD=postgres
    - POSTGRES_DB=demo
    - DATABASE_HOST=localhost
    networks:
    - iris-tier
    volumes:
    - ./postgres/initdb:/docker-entrypoint-initdb.d    

  sftp:
    image: atmoz/sftp
    hostname: sftp
    volumes:
    - ./upload:/home/foo/upload
    ports:
    - "2222:22"
    environment:
    - TZ=JST-9
    command: foo:pass:1000:1000
    networks:
    - iris-tier

  ftp:
    image: stilliard/pure-ftpd
    hostname: ftp
    ports:
    - "2121:21"
    - "30000-30009:30000-30009"
    volumes:
    - ./upload:/home/foo/upload
    environment:
    - PUBLICHOST=ftp
    - FTP_USER_NAME=foo
    - FTP_USER_PASS=pass
    - FTP_USER_HOME=/home/foo
    - FTP_USER_UID=1000
    - FTP_USER_GID=1000
    networks:
      - iris-tier
  
  postfix:
    image: catatnight/postfix
    hostname: postfix
    ports:
    - 25:25
    environment:
      - maildomain=example.com
      - smtp_user=foo:pass
    networks:
      - iris-tier

networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
      
