services: 
  oracle:
    init: true
    image: oracle/database:19.3.0-se2
    hostname: oracle
    ports:
    - 1521:1521
    environment:
    - TZ=JST-9
    - ORACLE_PWD=SYS
    networks:
    - iris-tier
    volumes:
    - ./oracle/initdb:/docker-entrypoint-initdb.d/setup
    - ./oracle/oradata:/opt/oracle/oradata
