version: '3.7'

services: 
  mysql:
    init: true
    image: mysql:8.0.19
    hostname: mysql
    ports:
    - 3306:3306
    environment:
    - TZ=JST-9
    - MYSQL_ROOT_PASSWORD=SYS
    - MYSQL_DATABASE=demo
    networks:
    - iris-tier
    volumes:
    - ./mysql/initdb:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql
    - ./mysql/cnf/my.cnf:/etc/mysql/conf.d/my.cnf