services: 
  iris:
    build: 
      context: .
      args:
        COMMIT_ID: ${COMMIT_ID}
    hostname: iris.example.org
    ports:
    - "63300:63300"  # foreground
    - "63301:63301"  # foreground
    command:
      --ISCAgent false --monitorCPF false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    networks:
    - iris-tier
    volumes:
    - ./ext:/opt/iris/ext
    - ./upload:/home/irisowner/upload
    - ./UserCPF:/home/irisowner/cpf
    depends_on:
    - postgres
    - sftp
    - ftp
    - mailserver
    - iris2
    secrets:
      - yahoo_cred
      - o365_cred
      - gmail_client_secret
      - o365_client_secret

  postgres:
    image: postgres:16.3
    hostname: postgres
    ports: 
    - "5432:5432"
    environment:
    - TZ=JST-9
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - PGPASSWORD=postgres
    - POSTGRES_DB=demo
    - DATABASE_HOST=localhost
    networks:
    - iris-tier
    volumes:
    - ./postgres/initdb:/docker-entrypoint-initdb.d    

  sftp:
    image: atmoz/sftp
    hostname: sftp
    volumes:
    - ./upload:/home/foo/upload
    ports:
    - "2222:22"
    environment:
    - TZ=JST-9
    command: foo:pass:1000:1000
    networks:
    - iris-tier

  ftp:
    image: stilliard/pure-ftpd
    hostname: ftp
    ports:
    - "2121:21"
    - "30000-30009:30000-30009"
    volumes:
    - ./upload:/home/foo/upload
    environment:
    - PUBLICHOST=ftp
    - FTP_USER_NAME=foo
    - FTP_USER_PASS=pass
    - FTP_USER_HOME=/home/foo
    - FTP_USER_UID=1000
    - FTP_USER_GID=1000
    networks:
      - iris-tier
  
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"
    volumes:
      - ./mailserver/docker-data/dms/mail-data/:/var/mail/
      - ./mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - ./mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - ./mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - iris-tier

  #smtp:
  #  build: 
  #    context: smtp
  #  hostname: smtp.example.com
  #  ports:
  #  - "25:25"
  #  environment:
  #    - maildomain=smtp.example.com
  #    - smtp_user=foo:pass
  #  networks:
  #    - iris-tier

  iris2:
    build: 
      context: msgbank
      args:
        COMMIT_ID: ${COMMIT_ID}
    hostname: iris2
    ports:
    - "52874:52773"
    command:
      --ISCAgent false --monitorCPF false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    networks:
    - iris-tier
    volumes:
    - ./UserCPF:/home/irisowner/cpf

  webgateway:
    #image: containers.intersystems.com/intersystems/webgateway:2024.1
    # docker compose log に不要なロギングが出力され続けるのを回避したいので以前のバージョンを使用する。
    image: containers.intersystems.com/intersystems/webgateway:2023.2
    init: true
    container_name: webgateway
    hostname: webgateway
    # 15秒間隔で出力され続ける下記メッセージを抑止するとされているオプションが2024.1時点で機能していない。
    # 2023.2の使用に切り替えたことに伴いコメントアウト. 
    # webgateway  | [INFO] Files /webgateway-shared/CSP.conf and /durable/webgateway/CSP.conf are the same; skipping copy
    # webgateway  | [INFO] Files /webgateway-shared/CSP.ini and /durable/webgateway/CSP.ini.last_merge are the same; skipping merge
    # command: --monitorConf false --monitorIni false
    ports:
    - "8882:80"
    - "8883:443"
    environment:
    #- ISC_DATA_DIRECTORY=/webgateway-shared/durable
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    # TZ環境変数はloggingに対して効果が無い模様。タイムスタンプがUTCになる。
    # 一応残しておく。 JSTが必要であればtzdataを使ったイメージをビルドする事。
    - TZ=JST-9
    volumes:
    - ./webgateway:/webgateway-shared
    networks:
    - iris-tier

networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
      
secrets:
  yahoo_cred:
    file: ./secrets/yahoo_cred.json
  o365_cred:
    file: ./secrets/o365_cred.json
  gmail_client_secret:
    file: ./secrets/gmail_client_secret.json
  o365_client_secret:
    file: ./secrets/o365_client_secret.json
