version: '3.5'

services: 
  iris:
    build: 
      context: .
    hostname: iris
    ports:
    - 51773:51773
    - 52773:52773
    environment:
    - TZ=JST-9
    networks:
    - iris-tier
    volumes:
    - ./ext:/opt/iris/ext
    depends_on:
    - postgres
    - sftp

  postgres:
    image: postgres:12.2-alpine
    hostname: postgres
    ports: 
    - "5432:5432"
    environment:
    - TZ=JST-9
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - PGPASSWORD=postgres
    - POSTGRES_DB=demo
    - DATABASE_HOST=localhost
    networks:
    - iris-tier
    volumes:
    - ./postgres/initdb:/docker-entrypoint-initdb.d    
    
  sftp:
    image: atmoz/sftp
    hostname: sftp
    volumes:
    - ./upload:/home/foo/upload
    ports:
    - "2222:22"
    environment:
    - TZ=JST-9
    command: foo:pass:1000:1000
    networks:
    - iris-tier
  
networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
      